version: "3.7"

services:
  hugo:
    image: ${SVC_HUGO_IMAGE}:${SVC_HUGO_VERSION}
    container_name: ${SVC_HUGO_CONTAINERNAME}
    environment:
      - "HUGO_DIR=${HUGO_DIR}"
      - "HUGO_URL=${HUGO_URL}"
      - "HUGO_APPEND_PORT=${HUGO_APPEND_PORT}"
      - "HUGO_BIND=${HUGO_BIND}"
      - "HUGO_OPTIONS=${HUGO_OPTIONS}"
    volumes:
      - "hugo_data:/data"
    ports:
      - "1313:1313"
    restart: always

# volumes
volumes:
  hugo_data:

